server.port: 8082
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/budget-tracker?serverTimezone=UTC
    username: budget
    password: budget@123